### ISSUE TITLE
ubuntu 18.04

### ISSUE THREAD

**Issue by rekkersNZ** [mdoyleaz/Logitech-G560-LED-Controller#4]
Havin issues trying to get this work work under ubuntu 18.04 
Stuffs a bit out of my league... 

Managed to get everything installed required it would seem... 
get a buncha errors.. looks like its to do with ubuntus python3 releases clashing with other stuff...

Any ideas.?

**Comment by ThomasLobker** [comment]
I think the installation and usage should be pretty easy on Ubuntu 18.04 and 20.04.

```
sudo apt install python3 python3-pip python3-usb
sudo pip3 install rpyc
git clone https://github.com/mdoyleaz/Logitech-G560-LED-Controller.git
cd Logitech-G560-LED-Controller
sudo python3 g560_service.py
```
And then while the service is running, open a new terminal and run the GUI.
```
cd Logitech-G560-LED-Controller
python3 g560_gui.py
```
